package todoapp.ui;

/** Server-rendered visual system: editorial field notes with an industrial edge. */
class TodoStyles {
	public static function css():String {
		return [
			":root { color-scheme: light; --paper: #f3eddf; --ink: #17211d; --quiet: #68716b; --rule: #b8b09f; --signal: #ef5a35; --moss: #587564; --panel: rgba(255, 252, 244, 0.84); --planning-open: #ef5a35; --planning-filed: #587564; --planning-grid: #c7bead; --background: #f3eddf; --foreground: #17211d; --card: #fffaf0; --card-foreground: #17211d; --primary: #17211d; --primary-foreground: #fffaf0; --secondary: #dce5dc; --secondary-foreground: #17211d; --muted: #e6dfd1; --muted-foreground: #68716b; --accent: #f9d8ce; --accent-foreground: #42170e; --destructive: #b73c28; --border: #b8b09f; --input: #8e897d; --ring: #ef5a35; --radius: .2rem; }",
			"* { box-sizing: border-box; }",
			"html { min-height: 100%; background: var(--paper); }",
			"body { min-height: 100vh; margin: 0; color: var(--ink); font-family: 'Avenir Next Condensed', 'Franklin Gothic Medium', sans-serif; background-image: linear-gradient(rgba(23, 33, 29, .055) 1px, transparent 1px), linear-gradient(90deg, rgba(23, 33, 29, .055) 1px, transparent 1px), radial-gradient(circle at 88% 8%, rgba(239, 90, 53, .18), transparent 28rem); background-size: 28px 28px, 28px 28px, auto; }",
			"a { color: inherit; }",
			"a:focus-visible { outline: 3px solid var(--signal); outline-offset: 4px; }",
			".shell { width: min(1120px, calc(100% - 32px)); margin: 0 auto; padding: 24px 0 64px; }",
			".masthead { display: grid; grid-template-columns: 1fr auto; align-items: end; gap: 24px; padding: 18px 0 22px; border-top: 6px solid var(--ink); border-bottom: 1px solid var(--ink); }",
			".brand { text-decoration: none; text-transform: uppercase; letter-spacing: .08em; font-weight: 800; font-size: clamp(1.1rem, 2vw, 1.45rem); }",
			".edition { color: var(--quiet); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .72rem; letter-spacing: .12em; text-transform: uppercase; }",
			".page { animation: settle .58s cubic-bezier(.22, 1, .36, 1) both; }",
			".hero { display: grid; grid-template-columns: minmax(0, 1.45fr) minmax(220px, .55fr); gap: clamp(32px, 7vw, 96px); padding: clamp(56px, 9vw, 112px) 0 48px; align-items: end; }",
			".eyebrow { margin: 0 0 14px; color: var(--signal); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .76rem; letter-spacing: .14em; text-transform: uppercase; }",
			"h1, h2 { margin: 0; font-family: 'Iowan Old Style', Baskerville, Georgia, serif; font-weight: 600; letter-spacing: -.045em; line-height: .94; }",
			"h1 { max-width: 760px; font-size: clamp(3.6rem, 10vw, 8.3rem); }",
			"h2 { font-size: clamp(2.7rem, 7vw, 5.8rem); }",
			".lede { max-width: 28rem; margin: 0; padding-top: 18px; border-top: 1px solid var(--rule); color: var(--quiet); font-size: clamp(1rem, 1.8vw, 1.25rem); line-height: 1.55; }",
			".intake-section { margin: 0 0 clamp(56px, 8vw, 88px); }",
			".intake-card { gap: 0; overflow: hidden; border: 1px solid var(--ink); border-top-width: 6px; background: color-mix(in srgb, var(--card) 86%, transparent); box-shadow: 12px 12px 0 rgba(23, 33, 29, .1); }",
			".intake-heading { display: grid; grid-template-columns: minmax(0, 1fr) minmax(220px, .42fr); gap: 32px; padding: 28px 30px 24px; border-bottom: 1px solid var(--rule); }",
			".intake-heading h2 { max-width: 580px; margin-top: 14px; font-size: clamp(2rem, 4vw, 3.9rem); line-height: 1; }",
			".intake-heading > p { align-self: end; max-width: 30rem; margin: 0; color: var(--quiet); line-height: 1.5; }",
			".intake-badge { border-color: var(--signal); color: var(--signal); border-radius: 0; }",
			".intake-content { padding: 28px 30px 30px; }",
			".intake-form { display: grid; grid-template-columns: minmax(0, 1.25fr) minmax(0, .55fr); gap: 22px 28px; }",
			".intake-field { display: grid; align-content: start; gap: 9px; }",
			".intake-field label { display: flex; justify-content: space-between; gap: 12px; font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .7rem; font-weight: 700; letter-spacing: .09em; text-transform: uppercase; }",
			".intake-field label span { color: var(--quiet); font-weight: 500; }",
			".intake-note { grid-row: span 2; }",
			".ledger-input, .intake-priority select { border-radius: 0; border-color: var(--ink); background: rgba(255, 252, 244, .74); font-family: 'Iowan Old Style', Baskerville, Georgia, serif; font-size: 1rem; }",
			".ledger-input { min-height: 44px; }",
			".ledger-textarea { min-height: 132px; line-height: 1.45; }",
			".intake-priority select { width: 100%; height: 44px; padding: 0 12px; color: var(--ink); }",
			".intake-commit { display: flex; align-items: center; gap: 16px; }",
			".intake-submit { min-width: 142px; border-radius: 0; text-transform: uppercase; letter-spacing: .07em; }",
			".mutation-status, .row-action-status { margin: 0; color: var(--quiet); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .68rem; line-height: 1.4; }",
			".mutation-status.is-error, .row-action-status.is-error { color: var(--destructive); }",
			".mutation-retry { min-height: 32px; padding: 6px 10px; border: 1px solid var(--signal); border-radius: 0; color: var(--signal); background: transparent; font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .64rem; font-weight: 700; letter-spacing: .06em; text-transform: uppercase; cursor: pointer; }",
			".mutation-retry:hover:not(:disabled) { color: var(--card); background: var(--signal); }",
			".mutation-retry:disabled { cursor: not-allowed; opacity: .48; }",
			".optimistic-draft { display: grid; gap: 8px; margin-top: 22px; padding: 18px 20px; border: 1px dashed var(--signal); background: color-mix(in srgb, var(--accent) 46%, transparent); animation: settle .2s ease both; }",
			".optimistic-draft[hidden] { display: none; }",
			".optimistic-draft > div { display: flex; justify-content: space-between; color: var(--signal); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .66rem; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; }",
			".optimistic-draft h3 { margin: 0; font-family: 'Iowan Old Style', Baskerville, Georgia, serif; font-size: 1.45rem; }",
			".optimistic-draft p { margin: 0; color: var(--quiet); }",
			".mutation-issues { grid-column: 1 / -1; display: grid; gap: 6px; margin: -4px 0 0; padding: 0; list-style: none; color: var(--destructive); font-size: .82rem; }",
			".mutation-issues:empty { display: none; }",
			".mutation-issues li { display: flex; gap: 10px; padding: 9px 12px; border-left: 3px solid currentColor; background: color-mix(in srgb, var(--destructive) 8%, transparent); }",
			".mutation-issues code { font-size: .72rem; font-weight: 700; }",
			".todo-workbench { display: grid; gap: 0; }",
			".command-register { position: relative; display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 28px; align-items: center; margin: 0 0 24px; padding: 20px 22px 20px 28px; overflow: hidden; border: 1px solid var(--ink); color: var(--card); background: var(--ink); box-shadow: 8px 8px 0 color-mix(in srgb, var(--signal) 24%, transparent); }",
			".command-register::before { position: absolute; inset: 0 auto 0 0; width: 6px; background: var(--signal); content: ''; }",
			".command-register-copy { display: grid; grid-template-columns: minmax(180px, .36fr) minmax(0, 1fr); gap: clamp(20px, 4vw, 48px); align-items: center; }",
			".command-register .eyebrow { margin: 0; color: #ff8b6d; }",
			".command-register-copy h2 { margin: 0; color: var(--card); font-size: clamp(1.6rem, 3vw, 2.65rem); letter-spacing: -.035em; line-height: 1; }",
			".command-register-copy div > p { max-width: 44rem; margin: 8px 0 0; color: color-mix(in srgb, var(--card) 67%, transparent); line-height: 1.45; }",
			".command-trigger { min-width: 214px; height: 50px; justify-content: space-between; border-radius: 0; border-color: color-mix(in srgb, var(--card) 64%, transparent); color: var(--card); background: transparent; font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .68rem; letter-spacing: .055em; text-transform: uppercase; box-shadow: none; }",
			".command-trigger:hover { border-color: var(--signal); color: var(--ink); background: var(--signal); }",
			".command-trigger:focus-visible { outline: 3px solid var(--signal); outline-offset: 4px; }",
			".command-trigger kbd, .command-dialog kbd { min-width: 26px; padding: 4px 6px; border: 1px solid currentColor; font: inherit; line-height: 1; text-align: center; }",
			".command-overlay { position: fixed; inset: 0; z-index: 80; background: rgba(11, 17, 14, .76); backdrop-filter: blur(7px) saturate(.72); }",
			".command-dialog { box-sizing: border-box; position: fixed; top: 50%; left: 50%; z-index: 81; display: flex; width: min(720px, calc(100vw - 32px)); max-height: min(780px, calc(100dvh - 40px)); overflow: hidden; border: 1px solid var(--ink); border-top: 8px solid var(--signal); border-radius: 0; color: var(--ink); background: var(--card); box-shadow: 18px 18px 0 rgba(0, 0, 0, .28); transform: translate(-50%, -50%); }",
			".command-dialog[data-state='open'] { animation: command-arrive .22s cubic-bezier(.22, 1, .36, 1) both; }",
			".command-dialog-head { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 20px; align-items: end; padding: 24px 26px 20px; border-bottom: 1px solid var(--ink); }",
			".command-dialog-head .eyebrow { margin: 0; }",
			".command-dialog-head > p:last-child { max-width: 18rem; margin: 0; color: var(--quiet); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .68rem; line-height: 1.45; text-align: right; }",
			".command-dialog [data-slot='command-input-wrapper'] { min-height: 64px; padding: 0 24px; border-bottom: 1px solid var(--rule); background: color-mix(in srgb, var(--paper) 62%, transparent); }",
			".command-dialog [data-slot='command-input-wrapper']:focus-within { box-shadow: inset 5px 0 0 var(--signal); }",
			".command-dialog [cmdk-input] { height: 64px; padding: 0; color: var(--ink); font-family: 'Iowan Old Style', Baskerville, Georgia, serif; font-size: 1.2rem; }",
			".command-dialog [cmdk-input]::placeholder { color: color-mix(in srgb, var(--quiet) 78%, transparent); }",
			".command-dialog [cmdk-list] { max-height: min(53vh, 430px); padding: 10px 0 14px; scroll-padding-block: 48px; }",
			".command-dialog [cmdk-group] { padding: 5px 12px 9px; }",
			".command-dialog [cmdk-group-heading] { padding: 10px 12px 7px; color: var(--quiet); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .62rem; font-weight: 700; letter-spacing: .13em; text-transform: uppercase; }",
			".command-dialog [cmdk-item] { min-height: 58px; margin: 2px 0; padding: 9px 12px; border: 1px solid transparent; border-radius: 0; color: var(--ink); }",
			".command-dialog [cmdk-item][data-selected='true'] { border-color: var(--ink); color: var(--card); background: var(--ink); box-shadow: 5px 0 0 var(--signal); }",
			".command-item-code { display: grid; flex: 0 0 38px; min-height: 38px; place-items: center; border: 1px solid currentColor; color: var(--signal); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .65rem; font-weight: 800; letter-spacing: .04em; }",
			"[cmdk-item][data-selected='true'] .command-item-code { color: #ff8b6d; }",
			".command-item-copy { display: grid; min-width: 0; gap: 3px; }",
			".command-item-copy strong { overflow: hidden; font-family: 'Iowan Old Style', Baskerville, Georgia, serif; font-size: 1rem; font-weight: 600; letter-spacing: -.01em; text-overflow: ellipsis; white-space: nowrap; }",
			".command-item-copy small { overflow: hidden; color: var(--quiet); font-size: .72rem; line-height: 1.35; text-overflow: ellipsis; white-space: nowrap; }",
			"[cmdk-item][data-selected='true'] .command-item-copy small { color: color-mix(in srgb, var(--card) 69%, transparent); }",
			".command-dialog [cmdk-separator] { height: 1px; margin: 3px 24px; background: var(--rule); }",
			".command-dialog [cmdk-empty] { display: grid; min-height: 170px; padding: 34px 26px; place-content: center; text-align: center; }",
			".command-dialog [cmdk-empty] p { margin: 0; font-family: 'Iowan Old Style', Baskerville, Georgia, serif; font-size: 1.45rem; font-weight: 600; }",
			".command-dialog [cmdk-empty] span { margin-top: 8px; color: var(--quiet); font-size: .8rem; }",
			".command-dialog-foot { display: flex; flex-wrap: wrap; gap: 18px; padding: 12px 24px 14px; border-top: 1px solid var(--rule); color: var(--quiet); background: color-mix(in srgb, var(--paper) 60%, transparent); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .62rem; letter-spacing: .06em; text-transform: uppercase; }",
			".command-dialog-foot span { display: inline-flex; gap: 7px; align-items: center; }",
			".discovery-panel { position: relative; display: grid; gap: 28px; margin: 0 0 42px; padding: clamp(24px, 4vw, 42px); overflow: hidden; border: 1px solid var(--ink); background: color-mix(in srgb, var(--card) 78%, transparent); box-shadow: 12px 12px 0 rgba(23, 33, 29, .1); }",
			".discovery-panel::after { position: absolute; top: -72px; right: -58px; width: 210px; aspect-ratio: 1; border: 1px solid color-mix(in srgb, var(--signal) 62%, transparent); content: ''; transform: rotate(18deg); box-shadow: inset 0 0 0 18px color-mix(in srgb, var(--card) 82%, transparent), inset 0 0 0 19px color-mix(in srgb, var(--signal) 62%, transparent); pointer-events: none; }",
			".discovery-intro { position: relative; z-index: 1; display: grid; grid-template-columns: minmax(0, 1.2fr) minmax(220px, .5fr); gap: 32px; align-items: end; }",
			".discovery-intro h2 { max-width: 650px; font-size: clamp(2.25rem, 5vw, 4.7rem); line-height: .98; }",
			".discovery-intro > p { max-width: 29rem; margin: 0; color: var(--quiet); line-height: 1.55; }",
			".discovery-grid { position: relative; z-index: 1; display: grid; grid-template-columns: minmax(230px, 1.25fr) repeat(3, minmax(150px, auto)); gap: 18px; align-items: end; padding-top: 22px; border-top: 1px solid var(--rule); }",
			".discovery-search, .lens-group { min-width: 0; }",
			".discovery-search { display: grid; gap: 8px; }",
			".discovery-search label, .lens-group legend { padding: 0; color: var(--quiet); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .67rem; font-weight: 700; letter-spacing: .09em; text-transform: uppercase; }",
			".discovery-input { height: 38px; min-height: 38px; border-color: var(--rule); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .78rem; }",
			".lens-group { margin: 0; padding: 0; border: 0; }",
			".lens-group > div { display: flex; flex-wrap: wrap; gap: 4px; margin-top: 8px; }",
			".lens-option { min-width: 0; height: 38px; padding-inline: 11px; border-radius: 0; box-shadow: none; font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .65rem; letter-spacing: .045em; text-transform: uppercase; }",
			".lens-option[aria-pressed='false'] { border: 1px solid transparent; color: var(--quiet); }",
			".lens-option[aria-pressed='true'] { background: var(--ink); color: var(--primary-foreground); }",
			".discovery-foot { position: relative; z-index: 1; display: flex; align-items: center; justify-content: space-between; gap: 18px; padding-top: 16px; border-top: 1px solid var(--rule); }",
			".discovery-foot p { margin: 0; color: var(--quiet); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .7rem; letter-spacing: .07em; text-transform: uppercase; }",
			".reset-lens { border-radius: 0; font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .66rem; letter-spacing: .05em; text-transform: uppercase; }",
			".planning-insight { display: grid; gap: 0; margin: 0 0 42px; border: 1px solid var(--ink); border-top-width: 6px; background: color-mix(in srgb, var(--card) 76%, transparent); box-shadow: 12px 12px 0 rgba(23, 33, 29, .1); }",
			".planning-copy { display: grid; grid-template-columns: minmax(0, 1.2fr) minmax(240px, .55fr); gap: 32px; align-items: end; padding: 28px 30px 26px; border-bottom: 1px solid var(--ink); }",
			".planning-copy h2 { max-width: 680px; font-size: clamp(2.2rem, 5vw, 4.5rem); line-height: .96; }",
			".planning-copy > p { max-width: 31rem; margin: 0; color: var(--quiet); line-height: 1.55; }",
			".planning-summary { display: grid; grid-template-columns: repeat(3, minmax(110px, .22fr)) minmax(260px, 1fr); border-bottom: 1px solid var(--ink); }",
			".planning-summary > p { display: grid; min-height: 112px; margin: 0; padding: 20px 24px; align-content: center; border-right: 1px solid var(--rule); }",
			".planning-summary > p:nth-child(3) { border-right-color: var(--ink); }",
			".planning-summary strong { font-family: 'Iowan Old Style', Baskerville, Georgia, serif; font-size: clamp(2.5rem, 5vw, 4.25rem); font-weight: 500; letter-spacing: -.06em; line-height: .8; }",
			".planning-summary span { margin-top: 12px; color: var(--quiet); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .62rem; font-weight: 700; letter-spacing: .11em; text-transform: uppercase; }",
			".planning-summary .planning-urgent { min-height: 0; border-right: 0; color: var(--quiet); font-family: 'Iowan Old Style', Baskerville, Georgia, serif; font-size: clamp(1.15rem, 2vw, 1.55rem); line-height: 1.28; }",
			".planning-summary .planning-urgent.is-active { color: var(--signal); background: color-mix(in srgb, var(--accent) 48%, transparent); }",
			".planning-visual { display: grid; grid-template-columns: minmax(0, 1.35fr) minmax(280px, .65fr); min-height: 286px; }",
			".planning-plot { display: grid; grid-template-rows: auto minmax(220px, 1fr); min-width: 0; padding: 20px 22px 18px 16px; border-right: 1px solid var(--ink); }",
			".planning-legend { display: flex; justify-content: flex-end; gap: 18px; padding: 0 4px 10px; color: var(--quiet); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .62rem; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; }",
			".planning-legend span { display: inline-flex; align-items: center; gap: 7px; }",
			".planning-legend span::before { width: 18px; height: 8px; background: var(--planning-open); content: ''; }",
			".planning-legend .is-filed::before { background: var(--planning-filed); }",
			".planning-chart { width: 100%; height: 100%; min-height: 220px; font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .68rem; }",
			".planning-chart:focus-visible { outline: 3px solid var(--signal); outline-offset: 3px; }",
			".planning-table-wrap { display: grid; align-content: stretch; min-width: 0; padding: 18px 22px 22px; }",
			".planning-table { width: 100%; border-collapse: collapse; font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .7rem; font-variant-numeric: tabular-nums; }",
			".planning-table caption { padding: 2px 0 16px; color: var(--quiet); line-height: 1.45; text-align: left; }",
			".planning-table th, .planning-table td { padding: 13px 8px; border-bottom: 1px solid var(--rule); text-align: right; }",
			".planning-table thead th { padding-top: 7px; color: var(--quiet); font-size: .6rem; letter-spacing: .08em; text-transform: uppercase; }",
			".planning-table th:first-child { padding-left: 0; text-align: left; }",
			".planning-table td:last-child, .planning-table th:last-child { padding-right: 0; }",
			".planning-table tbody th { color: var(--signal); font-weight: 800; letter-spacing: .07em; }",
			".ledger-head { display: flex; align-items: center; justify-content: space-between; gap: 20px; padding: 14px 0; border-top: 1px solid var(--ink); border-bottom: 1px solid var(--ink); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .72rem; letter-spacing: .1em; text-transform: uppercase; }",
			".workbench { position: relative; }",
			".todo-list { list-style: none; margin: 0; padding: 0; }",
			".todo-row { position: relative; display: grid; grid-template-columns: 38px 44px minmax(0, 1fr) auto minmax(176px, .3fr); gap: clamp(12px, 2vw, 28px); align-items: center; padding: 28px 10px; border-bottom: 1px solid var(--rule); background: transparent; transition: transform .2s ease, background-color .2s ease, box-shadow .2s ease, opacity .2s ease; }",
			".todo-row:hover { transform: translateX(8px); background: var(--panel); }",
			".todo-row.is-dragging { z-index: 2; background: var(--card); box-shadow: 10px 10px 0 rgba(23, 33, 29, .14); opacity: .78; }",
			".todo-row.is-dragging:hover { transform: none; }",
			".todo-row.is-drop-target { background: color-mix(in srgb, var(--accent) 52%, var(--panel)); }",
			".drag-handle { display: grid; width: 36px; height: 42px; place-items: center; border: 1px solid var(--rule); border-radius: 0; color: var(--quiet); background: color-mix(in srgb, var(--paper) 74%, transparent); cursor: grab; touch-action: none; transition: border-color .16s ease, color .16s ease, background-color .16s ease, transform .16s ease; }",
			".drag-handle:hover { border-color: var(--signal); color: var(--signal); background: var(--card); transform: translateY(-2px); }",
			".drag-handle:focus-visible { outline: 3px solid var(--signal); outline-offset: 3px; }",
			".drag-handle:active, .todo-row.is-dragging .drag-handle { color: var(--card); background: var(--signal); cursor: grabbing; }",
			".drag-handle span { font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: 1.05rem; line-height: 1; pointer-events: none; }",
			".sequence { color: var(--quiet); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .75rem; }",
			".todo-link { display: inline-block; text-decoration-thickness: 1px; text-underline-offset: 7px; font-family: 'Iowan Old Style', Baskerville, Georgia, serif; font-size: clamp(1.45rem, 3vw, 2.2rem); line-height: 1.08; }",
			".todo-note { max-width: 680px; margin: 10px 0 0; color: var(--quiet); line-height: 1.5; }",
			".stamp { min-width: 48px; padding: 8px 9px 6px; border: 1px solid currentColor; color: var(--signal); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .72rem; font-weight: 700; text-align: center; transform: rotate(-2deg); }",
			".todo-row.is-done .todo-link { color: var(--quiet); text-decoration-line: line-through; }",
			".todo-row.is-done .stamp { color: var(--moss); }",
			".todo-row:has(.row-actions[data-optimistic-completed='true']) .todo-link { color: var(--quiet); text-decoration-line: line-through; }",
			".todo-row.is-done:has(.row-actions[data-optimistic-completed='false']) .todo-link { color: inherit; text-decoration-line: none; }",
			".todo-row:has(.row-actions[data-optimistic-visible='false']) { opacity: .42; transform: translateX(14px); background: color-mix(in srgb, var(--destructive) 7%, transparent); }",
			".row-actions { display: grid; gap: 8px; justify-items: end; }",
			".row-action-buttons { display: flex; justify-content: flex-end; gap: 7px; }",
			".row-action { border-radius: 0; font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .66rem; letter-spacing: .05em; text-transform: uppercase; }",
			".remove-action { background: transparent; border: 1px solid color-mix(in srgb, var(--destructive) 54%, transparent); color: var(--destructive); box-shadow: none; }",
			".remove-action:hover { background: var(--destructive); color: white; }",
			".row-action-status { max-width: 185px; text-align: right; }",
			".row-action-feedback, .reorder-feedback { display: flex; align-items: center; justify-content: flex-end; gap: 10px; }",
			".reorder-status { margin: 12px 0 0; color: var(--quiet); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .68rem; letter-spacing: .035em; }",
			".reorder-status.is-error { color: var(--destructive); }",
			".empty-ledger { display: grid; justify-items: start; min-height: 300px; padding: clamp(40px, 7vw, 78px) clamp(20px, 5vw, 58px); border-bottom: 1px solid var(--ink); background: repeating-linear-gradient(-45deg, transparent, transparent 18px, rgba(23, 33, 29, .035) 18px, rgba(23, 33, 29, .035) 19px); }",
			".empty-ledger h3 { max-width: 650px; margin: 0; font-family: 'Iowan Old Style', Baskerville, Georgia, serif; font-size: clamp(2rem, 5vw, 4.2rem); font-weight: 600; letter-spacing: -.035em; line-height: 1; }",
			".empty-ledger > p:not(.eyebrow) { max-width: 34rem; margin: 20px 0 26px; color: var(--quiet); line-height: 1.55; }",
			".workbench.is-board { padding-top: 22px; }",
			".board-grid { display: grid; grid-template-columns: minmax(0, 1.45fr) minmax(280px, .65fr); gap: 18px; align-items: start; }",
			".board-lane { position: relative; min-width: 0; overflow: hidden; border: 1px solid var(--ink); border-top: 6px solid var(--signal); background: color-mix(in srgb, var(--panel) 84%, transparent); box-shadow: 8px 8px 0 rgba(23, 33, 29, .08); }",
			".board-lane-completed { border-top-color: var(--moss); background: color-mix(in srgb, var(--secondary) 52%, var(--panel)); }",
			".board-lane-head { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 20px; align-items: end; min-height: 122px; padding: 22px 24px 20px; border-bottom: 1px solid var(--ink); }",
			".board-lane-code { margin: 0 0 10px; color: var(--signal); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .66rem; font-weight: 700; letter-spacing: .12em; text-transform: uppercase; }",
			".board-lane-completed .board-lane-code { color: var(--moss); }",
			".board-lane-head h3 { margin: 0; font-family: 'Iowan Old Style', Baskerville, Georgia, serif; font-size: clamp(2rem, 4vw, 3.45rem); font-weight: 600; letter-spacing: -.04em; line-height: .94; }",
			".board-lane-count { display: grid; min-width: 64px; margin: 0; padding-left: 16px; border-left: 1px solid var(--rule); justify-items: end; }",
			".board-lane-count strong { font-family: 'Iowan Old Style', Baskerville, Georgia, serif; font-size: 2.85rem; font-weight: 500; letter-spacing: -.06em; line-height: .82; }",
			".board-lane-count span { margin-top: 8px; color: var(--quiet); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .6rem; letter-spacing: .1em; text-transform: uppercase; }",
			".board-list { display: grid; }",
			".board-lane .todo-row { grid-template-columns: 38px 34px minmax(0, 1fr); align-content: start; min-height: 228px; padding: 22px; border-bottom: 1px solid var(--rule); background: transparent; }",
			".board-lane .todo-row:last-child { border-bottom: 0; }",
			".board-lane .todo-row:hover { transform: translateY(-4px); background: var(--card); box-shadow: 0 8px 0 rgba(23, 33, 29, .07); }",
			".board-lane .todo-row > div:first-of-type { grid-column: 2 / -1; }",
			".board-lane .todo-note { min-height: 4.5em; }",
			".board-lane .stamp { grid-column: 2; justify-self: start; }",
			".board-lane .row-actions { grid-column: 3; align-self: end; justify-items: end; }",
			".board-lane-empty { display: grid; min-height: 228px; padding: 38px 24px; align-content: center; background: repeating-linear-gradient(-45deg, transparent, transparent 18px, rgba(23, 33, 29, .035) 18px, rgba(23, 33, 29, .035) 19px); }",
			".board-lane-empty p { margin: 0; font-family: 'Iowan Old Style', Baskerville, Georgia, serif; font-size: 1.45rem; font-weight: 600; letter-spacing: -.02em; }",
			".board-lane-empty span { max-width: 26rem; margin-top: 10px; color: var(--quiet); line-height: 1.5; }",
			".detail { display: grid; grid-template-columns: minmax(0, 1fr) minmax(240px, .42fr); gap: clamp(36px, 8vw, 110px); padding: clamp(64px, 11vw, 132px) 0 80px; }",
			".detail-copy { max-width: 760px; }",
			".detail-note { margin: 38px 0 0; padding: 26px 0 0; border-top: 1px solid var(--rule); color: var(--quiet); font-family: 'Iowan Old Style', Baskerville, Georgia, serif; font-size: clamp(1.25rem, 2.4vw, 1.8rem); line-height: 1.55; }",
			".failure-proof { position: relative; max-width: 620px; margin-top: 44px; padding: 24px 26px 26px; overflow: hidden; border: 1px solid var(--ink); background: color-mix(in srgb, var(--accent) 42%, var(--panel)); box-shadow: 8px 8px 0 rgba(23, 33, 29, .1); }",
			".failure-proof::before { position: absolute; inset: 0 auto 0 0; width: 5px; background: var(--signal); content: ''; }",
			".failure-proof h3 { margin: 0; font-family: 'Iowan Old Style', Baskerville, Georgia, serif; font-size: clamp(1.55rem, 3vw, 2.25rem); font-weight: 600; letter-spacing: -.025em; }",
			".failure-proof > p:not(.eyebrow) { max-width: 34rem; margin: 14px 0 20px; color: var(--quiet); line-height: 1.55; }",
			".failure-proof-trigger, .error-reset { border-radius: 0; border-color: var(--signal); color: var(--signal); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .68rem; letter-spacing: .07em; text-transform: uppercase; }",
			".failure-proof-trigger:hover, .error-reset:hover { background: var(--signal); color: var(--primary-foreground); }",
			".fact-sheet { align-self: end; margin: 0; border-top: 6px solid var(--ink); }",
			".fact { display: grid; grid-template-columns: 1fr auto; gap: 20px; padding: 15px 0; border-bottom: 1px solid var(--rule); }",
			".fact dt { color: var(--quiet); } .fact dd { margin: 0; font-family: ui-monospace, 'SFMono-Regular', monospace; }",
			".back-link { display: inline-block; margin-top: 34px; color: var(--signal); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .76rem; letter-spacing: .08em; text-transform: uppercase; text-underline-offset: 6px; }",
			".state-page { min-height: 70vh; display: grid; place-content: center; justify-items: start; padding: 72px 0; }",
			".state-code { color: var(--signal); font-family: ui-monospace, 'SFMono-Regular', monospace; font-size: .78rem; letter-spacing: .14em; text-transform: uppercase; }",
			".state-page p { max-width: 34rem; color: var(--quiet); font-size: 1.1rem; line-height: 1.6; }",
			".error-state { position: relative; min-height: 72vh; padding-left: clamp(0px, 5vw, 64px); }",
			".error-state::after { position: absolute; top: 20%; right: 8%; width: clamp(90px, 16vw, 190px); aspect-ratio: 1; border: 1px solid var(--signal); content: ''; transform: rotate(12deg); box-shadow: inset 0 0 0 14px var(--paper), inset 0 0 0 15px var(--signal); opacity: .55; pointer-events: none; }",
			".error-state .error-reset { margin-top: 10px; }",
			".loading-rule { width: min(480px, 80vw); height: 8px; overflow: hidden; background: var(--rule); }",
			".loading-rule::after { display: block; width: 42%; height: 100%; background: var(--signal); content: ''; animation: survey 1.1s ease-in-out infinite alternate; }",
			"@keyframes settle { from { opacity: 0; transform: translateY(18px); } to { opacity: 1; transform: translateY(0); } }",
			"@keyframes command-arrive { from { opacity: 0; transform: translate(-50%, calc(-50% + 18px)) scale(.985); } to { opacity: 1; transform: translate(-50%, -50%) scale(1); } }",
			"@keyframes survey { from { transform: translateX(-20%); } to { transform: translateX(160%); } }",
			"@media (max-width: 980px) { .discovery-grid { grid-template-columns: minmax(240px, 1fr) repeat(2, minmax(150px, auto)); } .lens-view { grid-column: 2; } }",
			"@media (max-width: 860px) { .intake-heading, .intake-form, .discovery-intro, .planning-copy { grid-template-columns: 1fr; } .intake-note { grid-row: auto; } .command-register { grid-template-columns: 1fr; } .command-register-copy { grid-template-columns: minmax(150px, .4fr) minmax(0, 1fr); } .command-trigger { width: 100%; } .discovery-grid { grid-template-columns: 1fr 1fr; } .lens-view { grid-column: auto; } .planning-summary { grid-template-columns: repeat(3, 1fr); } .planning-summary > p:nth-child(3) { border-right: 0; } .planning-summary .planning-urgent { grid-column: 1 / -1; border-top: 1px solid var(--ink); } .planning-visual { grid-template-columns: 1fr; } .planning-plot { border-right: 0; border-bottom: 1px solid var(--ink); } .todo-row { grid-template-columns: 38px 38px minmax(0, 1fr) auto; } .row-actions { grid-column: 3 / -1; justify-items: start; } .row-action-status { max-width: none; text-align: left; } .board-grid { grid-template-columns: 1fr; } }",
			"@media (max-width: 720px) { .hero, .detail { grid-template-columns: 1fr; } .hero { padding-top: 58px; } .intake-heading, .intake-content { padding-left: 20px; padding-right: 20px; } .intake-commit { align-items: flex-start; flex-direction: column; } .command-register { grid-template-columns: 1fr; padding: 20px 18px 22px 22px; } .command-register-copy { grid-template-columns: 1fr; gap: 12px; } .command-dialog { top: auto; bottom: 8px; width: calc(100vw - 16px); max-height: calc(100dvh - 16px); transform: translateX(-50%); box-shadow: 8px 8px 0 rgba(0, 0, 0, .28); } .command-dialog[data-state='open'] { animation-name: command-arrive-mobile; } .command-dialog-head { grid-template-columns: 1fr; padding: 18px 18px 15px; } .command-dialog-head > p:last-child { text-align: left; } .command-dialog [data-slot='command-input-wrapper'] { min-height: 56px; padding-inline: 18px; } .command-dialog [cmdk-input] { height: 56px; } .command-dialog [cmdk-list] { max-height: min(57vh, 430px); } .command-dialog-foot { gap: 12px; padding-inline: 18px; } .discovery-panel { padding: 22px 18px; } .discovery-panel::after { opacity: .38; } .discovery-grid { grid-template-columns: 1fr; } .discovery-search { grid-column: 1; } .discovery-foot { align-items: flex-start; flex-direction: column; } .planning-copy { padding: 24px 18px 22px; } .planning-summary { grid-template-columns: repeat(3, 1fr); } .planning-summary > p { min-height: 92px; padding: 16px 12px; } .planning-plot { min-height: 246px; padding-inline: 8px; } .planning-table-wrap { padding-inline: 18px; } .ledger-head { align-items: flex-start; flex-direction: column; } .todo-row { grid-template-columns: 38px 30px minmax(0, 1fr); padding-left: 0; padding-right: 0; } .stamp { grid-column: 3; justify-self: start; } .row-actions { grid-column: 3; } .row-action-buttons { flex-wrap: wrap; justify-content: flex-start; } .board-lane-head { min-height: 104px; padding: 18px 16px; } .board-lane .todo-row { grid-template-columns: 38px 30px minmax(0, 1fr); padding: 20px 16px; } .board-lane .todo-row > div:first-of-type { grid-column: 3; } .board-lane .stamp, .board-lane .row-actions { grid-column: 3; justify-items: start; } .detail { padding-top: 72px; } .fact-sheet { margin-top: 12px; } }",
			"@keyframes command-arrive-mobile { from { opacity: 0; transform: translate(-50%, 0) scale(.985); } to { opacity: 1; transform: translate(-50%, 0) scale(1); } }",
			"@media (prefers-reduced-motion: reduce) { *, *::before, *::after { scroll-behavior: auto !important; animation-duration: .01ms !important; animation-iteration-count: 1 !important; transition-duration: .01ms !important; } }"
		].join("\n");
	}
}
