package nextjs.raw;

import genes.ts.Undefinable;

/**
 * Server runtime values accepted by Next.js 16.2.12.
 *
 * Generated from `next/types.ServerRuntime`
 * (sha256:4f39fd954bd488855f3403e10efa7f2de15fa97baa423a8ecdb14ceb705238a5). Do not edit this file directly; update the
 * reviewed declaration surface and run `npm run bindings:next:update`.
 */
@:ts.type("\"nodejs\" | \"experimental-edge\" | \"edge\" | undefined")
typedef ServerRuntime = Undefinable<ServerRuntimeValue>;

/** Closed, typo-safe view of the upstream TypeScript string-literal union. */
@:ts.type("\"nodejs\" | \"experimental-edge\" | \"edge\"")
enum abstract ServerRuntimeValue(String) to String {
	final NodeJs = "nodejs";
	final ExperimentalEdge = "experimental-edge";
	final Edge = "edge";
}
