import {Register} from "../../genes/Register"

/**
 * Exact CSS class names reported by the configured CSS Modules processor.
 *
 * Source: styles/haxe-page.module.css
 * Generated by @genes-ts/tooling; edit the stylesheet, not this file.
 */
export type HaxePageStyles = {
	/**
	 * styles/haxe-page.module.css:1:2
	 */
	card: string,
	/**
	 * styles/haxe-page.module.css:6:2
	 */
	"error-state": string
}
