/**
 * Exact CSS Module export declared from the processor-owned manifest.
 * Source: styles/haxe-page.module.css
 * Generated by @genes-ts/tooling; edit the stylesheet, not this file.
 */
declare const styles: {
  readonly "card": string;
  readonly "error-state": string;
};

export default styles;
