import { createHash, randomUUID } from "node:crypto";
import {
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

import { effectiveOutputProfile } from "./config.js";
import { cliFailure } from "./cli-diagnostic.js";
import type { NextProjectDiscovery } from "./discovery.js";
import {
  GENES_TS_IDENTITY,
  HAXE_VERSION,
  NEXTJSHX_VERSION,
  NEXT_VERSION,
} from "./toolchain-identities.js";

const TOOLCHAIN_DIRECTORY = ".nextjshx/toolchain";
const TOOLCHAIN_SCHEMA_VERSION = 1;
const GENERATED_HEADER =
  "# Generated by NextJsHx setup. Do not edit; change nextjshx.config.json and rerun setup.";

interface ToolchainManifest {
  readonly schemaVersion: typeof TOOLCHAIN_SCHEMA_VERSION;
  readonly fingerprint: string;
  readonly files: Readonly<Record<string, string>>;
}

export interface ToolchainPublication {
  readonly action: "created" | "updated" | "unchanged" | "legacy";
  readonly hxmlPath: string;
  readonly fingerprint: string | null;
  readonly files: readonly string[];
}

export interface ToolchainOptions {
  readonly uuid?: () => string;
  readonly faultInjector?: (point: ToolchainFaultPoint) => void;
}

export type ToolchainFaultPoint =
  | "after-staging"
  | "after-backup"
  | "after-publish";

function sha256(value: string): string {
  return createHash("sha256").update(value, "utf8").digest("hex");
}

function fail(
  message: string,
  target: string,
  expected: string,
  actual: string,
  resolution: string,
): never {
  cliFailure(
    "NXHX-CLI-SETUP-0016",
    message,
    target,
    expected,
    actual,
    resolution,
  );
}

function portable(relative: string): string {
  return relative.split(path.sep).join("/");
}

function containedBy(parent: string, child: string): boolean {
  const relative = path.relative(parent, child);
  return (
    relative === "" ||
    (!relative.startsWith(`..${path.sep}`) &&
      relative !== ".." &&
      !path.isAbsolute(relative))
  );
}

function safeDirectory(
  root: string,
  workspaceRoot: string,
  relative: string,
): string {
  const absolute = path.resolve(root, ...relative.split("/"));
  if (!containedBy(workspaceRoot, absolute)) {
    fail(
      "A configured Haxe source root escapes the discovered workspace.",
      relative,
      "a workspace-contained source directory",
      absolute,
      "Move the source under the application package before running setup.",
    );
  }
  if (!existsSync(absolute)) {
    fail(
      "A configured Haxe source root is missing.",
      relative,
      "an existing real source directory",
      "missing",
      "Create the directory or remove it from $.haxe.sourceRoots.",
    );
  }
  const stats = lstatSync(absolute);
  if (stats.isSymbolicLink() || !stats.isDirectory()) {
    fail(
      "A configured Haxe source root is unsafe.",
      relative,
      "a real non-symlink directory",
      stats.isSymbolicLink() ? "symbolic link" : "non-directory entry",
      "Replace the entry with a reviewed real directory inside the package.",
    );
  }
  return absolute;
}

function haxePackages(
  root: string,
  workspaceRoot: string,
  sourceRoots: readonly string[],
): readonly string[] {
  const packages = new Set<string>();
  const visit = (directory: string): void => {
    const entries = readdirSync(directory, { withFileTypes: true }).sort(
      (left, right) => Buffer.from(left.name).compare(Buffer.from(right.name)),
    );
    for (const entry of entries) {
      const absolute = path.join(directory, entry.name);
      const stats = lstatSync(absolute);
      if (stats.isSymbolicLink()) {
        fail(
          "Setup refuses to discover Haxe modules through a symbolic link.",
          portable(path.relative(root, absolute)),
          "real source files and directories",
          "symbolic link",
          "Replace the link with reviewed project-contained source.",
        );
      }
      if (stats.isDirectory()) {
        visit(absolute);
        continue;
      }
      if (!stats.isFile() || !entry.name.endsWith(".hx")) {
        continue;
      }
      const source = readFileSync(absolute, "utf8");
      const match = /^\s*package\s+([A-Za-z_][A-Za-z0-9_.]*)\s*;/m.exec(
        source,
      );
      if (match === null) {
        if (
          /\bclass\s+[A-Za-z_][A-Za-z0-9_]*\b/.test(source) &&
          /\bstatic\s+function\s+main\s*\(\s*\)\s*:\s*Void\b/.test(source) &&
          !source.includes("@:next.")
        ) {
          // A recognized legacy empty entrypoint is deliberately not a DCE
          // root in the synthesized session. It is obsolete compatibility
          // source and never becomes application intent.
          continue;
        }
        fail(
          "Setup cannot safely infer a compiler include root for a default-package Haxe module.",
          portable(path.relative(root, absolute)),
          "an explicit non-empty Haxe package declaration",
          "no package declaration",
          "Place application modules in a named package so the compiler-owned plan can include them without scanning dependency packages.",
        );
      }
      packages.add((match[1] as string).split(".")[0] as string);
    }
  };
  for (const relative of sourceRoots) {
    visit(safeDirectory(root, workspaceRoot, relative));
  }
  return Object.freeze(
    [...packages].sort((left, right) =>
      Buffer.from(left).compare(Buffer.from(right)),
    ),
  );
}

function workspaceProvidesNextJsHx(
  discovery: NextProjectDiscovery,
): string | null {
  const manifest = path.join(discovery.workspaceRoot, "package.json");
  const source = path.join(discovery.workspaceRoot, "src");
  if (!existsSync(manifest) || !existsSync(source)) {
    return null;
  }
  try {
    const decoded: unknown = JSON.parse(readFileSync(manifest, "utf8"));
    if (
      typeof decoded === "object" &&
      decoded !== null &&
      !Array.isArray(decoded) &&
      (decoded as Record<string, unknown>).name === "nextjshx" &&
      lstatSync(source).isDirectory() &&
      !lstatSync(source).isSymbolicLink()
    ) {
      return portable(path.relative(discovery.packageRoot, source));
    }
  } catch {
    // An invalid workspace package is not accepted as an implicit source library.
  }
  return null;
}

function adapterPlanSource(): string {
  return [
    "package nextjshx_toolchain;",
    "",
    "#if macro",
    "import haxe.macro.Expr;",
    "import nextjshx.adapter.AdapterPlanRegistry;",
    "import nextjshx.app.PageLayoutMacro;",
    "import nextjshx.app.SpecialFileMacro;",
    "import nextjshx.cache.CacheFunctionMacro;",
    "import nextjshx.client.ClientComponentMacro;",
    "import nextjshx.mdx.MdxComponentsMacro;",
    "import nextjshx.route.RouteHandlerMacro;",
    "import nextjshx.server.ProxyMacro;",
    "import nextjshx.server.ServerFunctionMacro;",
    "",
    "/** Installs every released NextJsHx planner for the compiler-owned project session. */",
    "macro function install():Expr {",
    `\tAdapterPlanRegistry.install(".nextjshx/default-plan.json", "${NEXTJSHX_VERSION}", "${HAXE_VERSION}", "${GENES_TS_IDENTITY}", "${NEXT_VERSION}");`,
    "\tPageLayoutMacro.install();",
    "\tSpecialFileMacro.install();",
    "\tClientComponentMacro.install();",
    "\tServerFunctionMacro.install();",
    "\tRouteHandlerMacro.install();",
    "\tCacheFunctionMacro.install();",
    "\tProxyMacro.install();",
    "\tMdxComponentsMacro.install();",
    "\treturn macro null;",
    "}",
    "#end",
    "",
  ].join("\n");
}

function toolchainFiles(
  discovery: NextProjectDiscovery,
): ReadonlyMap<string, string> {
  const config = discovery.config;
  if (config === null || config.schemaVersion !== 2) {
    throw new Error("toolchainFiles requires schema-v2 application intent");
  }
  const packages = haxePackages(
    discovery.packageRoot,
    discovery.workspaceRoot,
    config.haxe.sourceRoots,
  );
  const localLibrary = workspaceProvidesNextJsHx(discovery);
  const profile = effectiveOutputProfile(config);
  const extension = profile.language === "typescript" ? "tsx" : "jsx";
  const hxml = [
    GENERATED_HEADER,
    "-lib genes-ts",
    ...(localLibrary === null
      ? ["-lib nextjshx"]
      : [`-cp ${localLibrary}`]),
    ...config.haxe.sourceRoots.map((root) => `-cp ${root}`),
    `-cp ${TOOLCHAIN_DIRECTORY}/src`,
    "--main nextjshx_toolchain.Main",
    `-js ${config.haxe.generatedRoot}/index.${extension}`,
    "",
    "--macro nextjshx_toolchain.AdapterPlan.install()",
    ...packages.map((name) => `--macro include('${name}')`),
    "-dce full",
    "",
  ].join("\n");
  return new Map([
    ["nextjshx.hxml", hxml],
    [
      "src/nextjshx_toolchain/Main.hx",
      [
        "package nextjshx_toolchain;",
        "",
        "/** Compiler-owned entry point; NextJsHx application code uses module owners instead. */",
        "class Main {",
        "\tpublic static function main():Void {}",
        "}",
        "",
      ].join("\n"),
    ],
    ["src/nextjshx_toolchain/AdapterPlan.hx", adapterPlanSource()],
  ]);
}

function parseManifest(file: string): ToolchainManifest {
  let decoded: unknown;
  try {
    decoded = JSON.parse(readFileSync(file, "utf8"));
  } catch (error) {
    fail(
      "The compiler-owned toolchain manifest is unreadable.",
      portable(file),
      "a valid setup-owned manifest",
      error instanceof Error ? error.message : "malformed JSON",
      "Do not repair generated toolchain files manually; remove the untrusted directory after review and rerun setup.",
    );
  }
  if (
    typeof decoded !== "object" ||
    decoded === null ||
    Array.isArray(decoded) ||
    (decoded as Record<string, unknown>).schemaVersion !==
      TOOLCHAIN_SCHEMA_VERSION ||
    typeof (decoded as Record<string, unknown>).fingerprint !== "string" ||
    typeof (decoded as Record<string, unknown>).files !== "object" ||
    (decoded as Record<string, unknown>).files === null ||
    Array.isArray((decoded as Record<string, unknown>).files)
  ) {
    fail(
      "The compiler-owned toolchain manifest has an unsupported shape.",
      portable(file),
      `schemaVersion ${TOOLCHAIN_SCHEMA_VERSION} with closed file digests`,
      "unsupported manifest",
      "Preserve the directory for inspection, then regenerate it with the matching NextJsHx setup command.",
    );
  }
  return decoded as ToolchainManifest;
}

function verifyOwnedTree(directory: string): ToolchainManifest | null {
  if (!existsSync(directory)) {
    return null;
  }
  const stats = lstatSync(directory);
  if (stats.isSymbolicLink() || !stats.isDirectory()) {
    fail(
      "The compiler-owned toolchain target is unsafe.",
      portable(directory),
      "an absent path or real setup-owned directory",
      stats.isSymbolicLink() ? "symbolic link" : "non-directory entry",
      "Move the blocking entry; setup never follows or overwrites it.",
    );
  }
  const manifestPath = path.join(directory, "manifest.json");
  if (!existsSync(manifestPath)) {
    fail(
      "Setup found an unowned compiler-toolchain directory.",
      portable(directory),
      "an absent directory or one with a valid setup manifest",
      "manifest.json missing",
      "Preserve and review the existing bytes; setup will not infer ownership from a directory name.",
    );
  }
  const manifest = parseManifest(manifestPath);
  const expectedEntries = new Set<string>(["manifest.json"]);
  for (const relative of Object.keys(manifest.files)) {
    expectedEntries.add(relative);
    let parent = path.posix.dirname(relative);
    while (parent !== ".") {
      expectedEntries.add(parent);
      parent = path.posix.dirname(parent);
    }
  }
  const visit = (current: string): void => {
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const absolute = path.join(current, entry.name);
      const relative = portable(path.relative(directory, absolute));
      const entryStats = lstatSync(absolute);
      if (entryStats.isSymbolicLink()) {
        fail(
          "The compiler-owned toolchain contains an unsafe symbolic link.",
          relative,
          "only manifest-owned regular files and directories",
          "symbolic link",
          "Preserve the bytes for review, then remove the untrusted toolchain directory before setup.",
        );
      }
      if (!expectedEntries.has(relative)) {
        fail(
          "The compiler-owned toolchain contains an unowned entry.",
          relative,
          "only paths recorded or implied by manifest.json",
          entryStats.isDirectory() ? "unowned directory" : "unowned file",
          "Move the unowned entry out of .nextjshx/toolchain; setup never deletes unknown bytes.",
        );
      }
      if (entryStats.isDirectory()) {
        visit(absolute);
      }
    }
  };
  visit(directory);
  for (const [relative, digest] of Object.entries(manifest.files)) {
    const absolute = path.resolve(directory, ...relative.split("/"));
    if (!containedBy(directory, absolute) || !existsSync(absolute)) {
      fail(
        "A setup-owned compiler file is missing or escapes its toolchain root.",
        relative,
        "the exact manifest-owned regular file",
        "missing or escaped",
        "Restore the generated bytes or explicitly remove the reviewed toolchain directory before setup.",
      );
    }
    const fileStats = lstatSync(absolute);
    const actual =
      fileStats.isFile() && !fileStats.isSymbolicLink()
        ? sha256(readFileSync(absolute, "utf8"))
        : "unsafe-entry";
    if (actual !== digest) {
      fail(
        "A setup-owned compiler file was modified.",
        relative,
        digest,
        actual,
        "Change application intent in nextjshx.config.json; do not patch compiler-owned HXML or bootstrap source.",
      );
    }
  }
  return manifest;
}

function desiredManifest(
  files: ReadonlyMap<string, string>,
): ToolchainManifest {
  const digests = Object.fromEntries(
    [...files].map(([relative, content]) => [relative, sha256(content)]),
  );
  const fingerprint = sha256(
    [...files]
      .map(([relative, content]) => `${relative}\0${content}`)
      .join("\0"),
  );
  return Object.freeze({
    schemaVersion: TOOLCHAIN_SCHEMA_VERSION,
    fingerprint,
    files: Object.freeze(digests),
  });
}

/**
 * Synthesizes and transactionally publishes the compiler-owned Haxe session.
 *
 * NextJsHx commands call this before compilation, so a checked-in application
 * config is sufficient on a clean machine. `setup` calls the same function and
 * reports the resulting ownership state.
 */
export function ensureCompilerToolchain(
  discovery: NextProjectDiscovery,
  options: ToolchainOptions = {},
): ToolchainPublication {
  const config = discovery.config;
  if (config === null) {
    throw new Error("ensureCompilerToolchain requires discovered config");
  }
  if (config.schemaVersion === 1) {
    const hxml = config.haxe.legacyHxml;
    if (hxml === undefined) {
      throw new Error("schema-v1 config lost its legacy HXML");
    }
    return Object.freeze({
      action: "legacy",
      hxmlPath: path.resolve(discovery.packageRoot, hxml),
      fingerprint: null,
      files: Object.freeze([]),
    });
  }

  const relativeDirectory = TOOLCHAIN_DIRECTORY;
  const directory = path.join(
    discovery.packageRoot,
    ...relativeDirectory.split("/"),
  );
  const previous = verifyOwnedTree(directory);
  const files = toolchainFiles(discovery);
  const manifest = desiredManifest(files);
  if (previous?.fingerprint === manifest.fingerprint) {
    return Object.freeze({
      action: "unchanged",
      hxmlPath: path.join(directory, "nextjshx.hxml"),
      fingerprint: manifest.fingerprint,
      files: Object.freeze([...files.keys(), "manifest.json"]),
    });
  }

  const control = path.join(discovery.packageRoot, ".nextjshx");
  if (!existsSync(control)) {
    mkdirSync(control, { mode: 0o700 });
  }
  const controlStats = lstatSync(control);
  if (controlStats.isSymbolicLink() || !controlStats.isDirectory()) {
    fail(
      "The NextJsHx control root is unsafe.",
      ".nextjshx",
      "a real private directory",
      controlStats.isSymbolicLink() ? "symbolic link" : "non-directory entry",
      "Move the blocking entry before setup.",
    );
  }

  const id = (options.uuid ?? randomUUID)();
  const staging = path.join(control, `.toolchain-${id}.staging`);
  const backup = path.join(control, `.toolchain-${id}.backup`);
  if (existsSync(staging) || existsSync(backup)) {
    fail(
      "The setup transaction workspace already exists.",
      portable(path.relative(discovery.packageRoot, staging)),
      "fresh transaction paths",
      "collision",
      "Preserve the colliding entries for inspection and rerun setup with a fresh transaction identity.",
    );
  }
  mkdirSync(staging, { recursive: false, mode: 0o700 });
  let backedUp = false;
  let published = false;
  try {
    for (const [relative, content] of files) {
      const absolute = path.join(staging, ...relative.split("/"));
      mkdirSync(path.dirname(absolute), { recursive: true, mode: 0o700 });
      writeFileSync(absolute, content, { encoding: "utf8", flag: "wx", mode: 0o600 });
    }
    writeFileSync(
      path.join(staging, "manifest.json"),
      `${JSON.stringify(manifest, null, 2)}\n`,
      { encoding: "utf8", flag: "wx", mode: 0o600 },
    );
    options.faultInjector?.("after-staging");
    if (existsSync(directory)) {
      renameSync(directory, backup);
      backedUp = true;
    }
    options.faultInjector?.("after-backup");
    renameSync(staging, directory);
    published = true;
    options.faultInjector?.("after-publish");
    if (backedUp) {
      rmSync(backup, { recursive: true, force: false });
      backedUp = false;
    }
  } catch (error) {
    if (published && existsSync(directory)) {
      rmSync(directory, { recursive: true, force: false });
      published = false;
    }
    if (backedUp && existsSync(backup)) {
      renameSync(backup, directory);
      backedUp = false;
    }
    throw error;
  } finally {
    if (existsSync(staging)) {
      rmSync(staging, { recursive: true, force: false });
    }
    if (existsSync(backup) && !backedUp) {
      rmSync(backup, { recursive: true, force: false });
    }
  }
  return Object.freeze({
    action: previous === null ? "created" : "updated",
    hxmlPath: path.join(directory, "nextjshx.hxml"),
    fingerprint: manifest.fingerprint,
    files: Object.freeze([...files.keys(), "manifest.json"]),
  });
}
