"use client";
// Generated by NextJsHx from special_file_fixture.ErrorView.render. Implementation graph: sha256:983d58d1406fa406ba687098934605edd6ad8eb8973442444d941a0250610850.
import { ErrorView } from "../../../src-gen/special_file_fixture/ErrorView";
import type { JSX } from "react";
const NextJsHxDefault: (props: {
    error: Error & {
        digest?: string;
    };
    reset: () => void;
}) => JSX.Element = ErrorView.render;
export default NextJsHxDefault;
