// Generated by NextJsHx from request_proxy_fixture.RequestProxy.proxy. Implementation graph: sha256:1a786907934a0d404813670779e0c547c31f77ebb8d7b2cc8f987d2bfd3f49b5.
import { RequestProxy } from "./src-gen/request_proxy_fixture/RequestProxy";
import type { NextProxy as NextJsHxProxy } from "next/server";
import type { ProxyConfig as NextJsHxProxyConfig } from "next/server";
export const proxy: NextJsHxProxy = RequestProxy.proxy;
export const config: NextJsHxProxyConfig = { matcher: ["/haxe", "/products/:path*"] };
