// Generated by NextJsHx from special_file_fixture.LoadingView.render. Implementation graph: sha256:64c07e5bf2d11974d9815181ca7f62c26873a9dcd0a7b70926b1b3e3a11f8ac7.
import { LoadingView } from "../../../src-gen/special_file_fixture/LoadingView";
import type { JSX } from "react";
const NextJsHxDefault: () => JSX.Element = LoadingView.render;
export default NextJsHxDefault;
