// Generated by NextJsHx from app.InterceptedPhotoPage.render. Implementation graph: sha256:2376503ae05a6d5ba2bd03373059fe9693c27cf2ed72b64eea84aaf36bdfd510.
import { InterceptedPhotoPage } from "../../../../src-gen/app/InterceptedPhotoPage";
import type { JSX } from "react";
const NextJsHxDefault: (props: PageProps<"/photo/[id]">) => JSX.Element = InterceptedPhotoPage.render;
export default NextJsHxDefault;
