// Generated by NextJsHx from app.HaxePage.render. Implementation graph: sha256:720fa72abca8ca23d7c259b92e9b2df4dacdd3841bc1504161f2ad801033602f.
import { HaxePage } from "../../src-gen/app/HaxePage";
import type { Metadata } from "next";
import type { JSX } from "react";
const NextJsHxDefault: (props: PageProps<"/haxe">) => JSX.Element = HaxePage.render;
export default NextJsHxDefault;
export const metadata: Metadata = HaxePage.metadata;
export const maxDuration = 5;
export const preferredRegion = "home";
export const revalidate = false;
export const runtime = "nodejs";
