// Generated by NextJsHx from special_file_fixture.LoadingView.render. Implementation graph: sha256:0c40ee1852c33d51063568ebe3f46eee79e0b2ef8524bd02800d7eb7c09eaa70.
import { LoadingView } from "../../../src-gen/special_file_fixture/LoadingView";
import type { JSX } from "react";
const NextJsHxDefault: () => JSX.Element = LoadingView.render;
export default NextJsHxDefault;
