// Generated by NextJsHx from app.RootLayout.render. Implementation graph: sha256:460e800c84fafb96517229932c98b29ffacf5e079027545e22d0ed39b1a7cc19.
import "./globals.css";
import { RootLayout } from "../src-gen/app/RootLayout";
import type { JSX } from "react";
const NextJsHxDefault: (props: LayoutProps<"/">) => JSX.Element = RootLayout.render;
export default NextJsHxDefault;
