// Generated by NextJsHx from app.PhotoPage.render. Implementation graph: sha256:495311b02b599e388e528077181cfc781a4154301c4b0b5dad97d99b827087b6.
import { PhotoPage } from "../../../src-gen/app/PhotoPage";
import type { JSX } from "react";
const NextJsHxDefault: (props: PageProps<"/photo/[id]">) => JSX.Element = PhotoPage.render;
export default NextJsHxDefault;
