// Generated by NextJsHx from app.HaxePage.render. Implementation graph: sha256:7750b748de7b974774e4582d6f0ac823bf8c56e48eef0758d72ef630aeb87ec2.
import { HaxePage } from "../../src-gen/app/HaxePage";
import type { Metadata } from "next";
import type { JSX } from "react";
const NextJsHxDefault: (props: PageProps<"/haxe">) => JSX.Element = HaxePage.render;
export default NextJsHxDefault;
export const metadata: Metadata = HaxePage.metadata;
export const maxDuration = 5;
export const preferredRegion = "home";
export const revalidate = false;
export const runtime = "nodejs";
