// Generated by NextJsHx from app.PhotoPage.render. Implementation graph: sha256:0d5121cbde8aa00e5856a05e229d0131b0354c75b8e0b7e173df41c4c5e7ab85.
import { PhotoPage } from "../../../src-gen/app/PhotoPage";
import type { JSX } from "react";
const NextJsHxDefault: (props: PageProps<"/photo/[id]">) => JSX.Element = PhotoPage.render;
export default NextJsHxDefault;
