// Generated by NextJsHx from app.ProductPage.render. Implementation graph: sha256:def468fab89d03035ee38a0fe6f88784cedff51d6338e5c8a89e82197281735e.
import { ProductPage } from "../../../src-gen/app/ProductPage";
import type { Metadata } from "next";
import type { ResolvingMetadata } from "next";
import type { JSX } from "react";
const NextJsHxDefault: (props: PageProps<"/products/[slug]">) => JSX.Element = ProductPage.render;
export default NextJsHxDefault;
export const generateMetadata: (props: PageProps<"/products/[slug]">, parent: ResolvingMetadata) => Promise<Metadata> = ProductPage.generateMetadata;
export const generateStaticParams: () => Promise<Array<Awaited<PageProps<"/products/[slug]">["params"]>>> = ProductPage.generateStaticParams;
export const dynamicParams = false;
export const maxDuration = 10;
export const preferredRegion = ["iad1", "sfo1"];
export const revalidate = 60;
