"use client";
// Generated by NextJsHx from special_file_fixture.ErrorView.render. Implementation graph: sha256:3205a149c90f5400fef0029116a115e1b56fa271c46f0468af33fee720d3610e.
import { ErrorView } from "../../../src-gen/special_file_fixture/ErrorView";
import type { JSX } from "react";
const NextJsHxDefault: (props: {
    error: Error & {
        digest?: string;
    };
    reset: () => void;
}) => JSX.Element = ErrorView.render;
export default NextJsHxDefault;
