// Generated by NextJsHx from special_file_fixture.NotFoundView.render. Implementation graph: sha256:ad613f5ac48ebbed8913bdadb8967ce1d3d8d76b1248e58ebb05dad261c23fd2.
import { NotFoundView } from "../../../src-gen/special_file_fixture/NotFoundView";
import type { JSX } from "react";
const NextJsHxDefault: () => JSX.Element = NotFoundView.render;
export default NextJsHxDefault;
