// Generated by NextJsHx from app.ProductPage.render. Implementation graph: sha256:39f4df43ae4dac45a99cc79550122f95d87ec89e4644650b644faeafd823309f.
import { ProductPage } from "../../../src-gen/app/ProductPage";
import type { Metadata } from "next";
import type { ResolvingMetadata } from "next";
import type { JSX } from "react";
const NextJsHxDefault: (props: PageProps<"/products/[slug]">) => JSX.Element = ProductPage.render;
export default NextJsHxDefault;
export const generateMetadata: (props: PageProps<"/products/[slug]">, parent: ResolvingMetadata) => Promise<Metadata> = ProductPage.generateMetadata;
export const generateStaticParams: () => Promise<Array<Awaited<PageProps<"/products/[slug]">["params"]>>> = ProductPage.generateStaticParams;
export const dynamicParams = false;
export const maxDuration = 10;
export const preferredRegion = ["iad1", "sfo1"];
export const revalidate = 60;
