// Generated by NextJsHx from app.RootLayout.render. Implementation graph: sha256:1fbcce3b88000d5c806cba8a34530f63fe9fd859f6d844d37be5275f1c8c1d5a.
import { RootLayout } from "../src-gen/app/RootLayout";
import type { JSX } from "react";
const NextJsHxDefault: (props: LayoutProps<"/">) => JSX.Element = RootLayout.render;
export default NextJsHxDefault;
