// Generated by NextJsHx from special_file_fixture.NotFoundView.render. Implementation graph: sha256:65e8c0d46a123bec8f28764ea6e414d31a48b6287cdc9f693263218eb997c532.
import { NotFoundView } from "../../../src-gen/special_file_fixture/NotFoundView";
import type { JSX } from "react";
const NextJsHxDefault: () => JSX.Element = NotFoundView.render;
export default NextJsHxDefault;
