// Generated by NextJsHx from app.InterceptedPhotoPage.render. Implementation graph: sha256:7836e9c5f0b9518a04a5fefa8526a0a32b20c835e85851428135869e6ecc41ec.
import { InterceptedPhotoPage } from "../../../../src-gen/app/InterceptedPhotoPage";
import type { JSX } from "react";
const NextJsHxDefault: (props: PageProps<"/photo/[id]">) => JSX.Element = InterceptedPhotoPage.render;
export default NextJsHxDefault;
