// Generated by NextJsHx from request_proxy_fixture.RequestProxy.proxy. Implementation graph: sha256:a3c7cc99502545e24bd6934acc956a5c4af047e53b88594219a8385be1ecaaec.
import { RequestProxy } from "./src-gen/request_proxy_fixture/RequestProxy";
import type { NextProxy as NextJsHxProxy } from "next/server";
import type { ProxyConfig as NextJsHxProxyConfig } from "next/server";
export const proxy: NextJsHxProxy = RequestProxy.proxy;
export const config: NextJsHxProxyConfig = { matcher: ["/haxe", "/products/:path*"] };
