"use client";
// Generated by NextJsHx from special_file_fixture.ErrorView.render. Implementation graph: sha256:06b8a5eb01d8002d3d491f504666c87605a97066cb8b7b7d512fa1c45428cffc.
import { ErrorView } from "../../../src-gen/special_file_fixture/ErrorView";
import type { JSX } from "react";
const NextJsHxDefault: (props: {
    error: Error & {
        digest?: string;
    };
    reset: () => void;
}) => JSX.Element = ErrorView.render;
export default NextJsHxDefault;
