// Generated by NextJsHx from app.FeedPage.render. Implementation graph: sha256:566d0c54411a3255df5f58fff1dfe9eba331d09c3b31cbfa42124612347778f6.
import { FeedPage } from "../../src-gen/app/FeedPage";
import type { JSX } from "react";
const NextJsHxDefault: (props: PageProps<"/feed">) => JSX.Element = FeedPage.render;
export default NextJsHxDefault;
