// Generated by NextJsHx from app.PhotoPage.render. Implementation graph: sha256:7d504a1c3b155e0f40489110dc7fe694cb4b090a63fb1ca7aa1b576fa83edc3c.
import { PhotoPage } from "../../../src-gen/app/PhotoPage";
import type { JSX } from "react";
const NextJsHxDefault: (props: PageProps<"/photo/[id]">) => JSX.Element = PhotoPage.render;
export default NextJsHxDefault;
