// Generated by NextJsHx from app.ProductPage.render. Implementation graph: sha256:65d7c79f6225357c3d471e0cf0d2d8a4a3efa9ea5af7fe32b15549e83cc5a5b9.
import { ProductPage } from "../../../src-gen/app/ProductPage";
import type { Metadata } from "next";
import type { ResolvingMetadata } from "next";
import type { JSX } from "react";
const NextJsHxDefault: (props: PageProps<"/products/[slug]">) => JSX.Element = ProductPage.render;
export default NextJsHxDefault;
export const generateMetadata: (props: PageProps<"/products/[slug]">, parent: ResolvingMetadata) => Promise<Metadata> = ProductPage.generateMetadata;
export const generateStaticParams: () => Promise<Array<Awaited<PageProps<"/products/[slug]">["params"]>>> = ProductPage.generateStaticParams;
export const dynamicParams = false;
export const maxDuration = 10;
export const preferredRegion = ["iad1", "sfo1"];
export const revalidate = 60;
