// Generated by NextJsHx from app.FeedPage.render. Implementation graph: sha256:92c343735789266d1a5c872e93ef13b295f2f7739a1a36cdd708f082b22969ee.
import { FeedPage } from "../../src-gen/app/FeedPage";
import type { JSX } from "react";
const NextJsHxDefault: (props: PageProps<"/feed">) => JSX.Element = FeedPage.render;
export default NextJsHxDefault;
