// Generated by NextJsHx from request_proxy_fixture.RequestProxy.proxy. Implementation graph: sha256:1a0c60ac23537199b2ee3cccec816eb811242b42a8c9ae03360e76390f5d8b0d.
import { RequestProxy } from "./src-gen/request_proxy_fixture/RequestProxy";
import type { NextProxy as NextJsHxProxy } from "next/server";
import type { ProxyConfig as NextJsHxProxyConfig } from "next/server";
export const proxy: NextJsHxProxy = RequestProxy.proxy;
export const config: NextJsHxProxyConfig = { matcher: ["/haxe", "/products/:path*"] };
