// Generated by NextJsHx from special_file_fixture.NotFoundView.render. Implementation graph: sha256:06e601675e7312b961f26380c49d78d0900fc0e689e4dde269c48f9ade485562.
import { NotFoundView } from "../../../src-gen/special_file_fixture/NotFoundView";
import type { JSX } from "react";
const NextJsHxDefault: () => JSX.Element = NotFoundView.render;
export default NextJsHxDefault;
