// Generated by NextJsHx from app.ModalDefault.render. Implementation graph: sha256:db78623e608e4f58cb8be4ec6f5af4e8be4cfc6a805a3667e89a2968db3588c4.
import { ModalDefault } from "../../src-gen/app/ModalDefault";
import type { JSX } from "react";
const NextJsHxDefault: () => JSX.Element = ModalDefault.render;
export default NextJsHxDefault;
