// Generated by NextJsHx from app.ModalDefault.render. Implementation graph: sha256:16d4c208e1ebbc5a46b543ccc23150814b130bc041574abb9838bd3c84c92eda.
import { ModalDefault } from "../../src-gen/app/ModalDefault";
import type { JSX } from "react";
const NextJsHxDefault: () => JSX.Element = ModalDefault.render;
export default NextJsHxDefault;
