// Generated by NextJsHx from app.InterceptedPhotoPage.render. Implementation graph: sha256:b24136b5ea663ab8b0c05057b57ea3b1ad50646bd0e087a40a601be3532fe858.
import { InterceptedPhotoPage } from "../../../../src-gen/app/InterceptedPhotoPage";
import type { JSX } from "react";
const NextJsHxDefault: (props: PageProps<"/photo/[id]">) => JSX.Element = InterceptedPhotoPage.render;
export default NextJsHxDefault;
