// Generated by NextJsHx from app.RootLayout.render. Implementation graph: sha256:5ca406372e25292b9997805e7a42195f33867e0d85ef79280a80856e73417876.
import { RootLayout } from "../src-gen/app/RootLayout";
import type { JSX } from "react";
const NextJsHxDefault: (props: LayoutProps<"/">) => JSX.Element = RootLayout.render;
export default NextJsHxDefault;
