// Generated by NextJsHx from special_file_fixture.LoadingView.render. Implementation graph: sha256:90aaa270d02c9981e948278ef0d2f3749c89bdf00fb1673d0afce098cf1b7a9b.
import { LoadingView } from "../../../src-gen/special_file_fixture/LoadingView";
import type { JSX } from "react";
const NextJsHxDefault: () => JSX.Element = LoadingView.render;
export default NextJsHxDefault;
