// Generated by NextJsHx from app.HaxePage.render. Implementation graph: sha256:58373998dd42c060a869c99a3624140deb2a64168fed058496778e05d89bb8d5.
import { HaxePage } from "../../src-gen/app/HaxePage";
import type { Metadata } from "next";
import type { JSX } from "react";
const NextJsHxDefault: (props: PageProps<"/haxe">) => JSX.Element = HaxePage.render;
export default NextJsHxDefault;
export const metadata: Metadata = HaxePage.metadata;
export const maxDuration = 5;
export const preferredRegion = "home";
export const revalidate = false;
export const runtime = "nodejs";
