// Generated by NextJsHx from app.ModalDefault.render. Implementation graph: sha256:3ae90bc992bffdac09736a69b2c8a439908844ea574a5ce47965a65d718fb33f.
import { ModalDefault } from "../../src-gen/app/ModalDefault";
import type { JSX } from "react";
const NextJsHxDefault: () => JSX.Element = ModalDefault.render;
export default NextJsHxDefault;
