// Generated by NextJsHx from app.FeedPage.render. Implementation graph: sha256:df173cde84df4592c7c1d886ef54718b02e23e940b6b0c0dd20bff9bc368b190.
import { FeedPage } from "../../src-gen/app/FeedPage";
import type { JSX } from "react";
const NextJsHxDefault: (props: PageProps<"/feed">) => JSX.Element = FeedPage.render;
export default NextJsHxDefault;
